version: '3.9'

volumes:
  es-data:
  kafka_data:
    driver: local

# all dockers on the same default network, kafka docker has an alias on the network: kafkazoo.wme
# advertised host by kafka (for brokers) is kafkazoo.wme
# the spring boot apps connect to localhost, will get brokers
#  with kafkazoo.wme back, so this setup needs localhost entry in /etc/hosts
# akhq runs in its own docker, and connects via the default network using just kafka:9092

services:
#-----------------------------------------------------
#  zookeeper:
#    image: bitnami/zookeeper:latest
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#
#  kafka:
#    image: bitnami/kafka:latest
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      - KAFKA_BROKER_ID=1
#      - KAFKA_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafkazoo.wme:9092
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper
#    networks:
#      default:
#        aliases:
#          - kafkazoo.wme
  kafka:
    image: 'bitnami/kafka:3.5'
    container_name: kafka
    ports:
      - '9092:9092'
    volumes:
      - kafka_data:/bitnami
    environment:
      #kraft
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@127.0.0.1:9093
      # listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafkazoo.wme:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      default:
        aliases:
          - kafkazoo.wme
#-----------------------------------------------------
  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    ports:
      - "8080:8080"
    volumes:
      - ./akhq.yml:/app/application.yml
    depends_on:
      - kafka
#-----------------------------------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/es-data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
#-----------------------------------------------------
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.6
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
#-----------------------------------------------------